# This file was generated by GoReleaser. DO NOT EDIT.
cask "neo" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "c2dd58c3745a0d8c3657d4a77d25c01c0abde5390bdd27236a190b5e72132a2b"
      url "https://github.com/owainlewis/neo/releases/download/v#{version}/neo_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c90dbcdf46e096434bb9b980946c9cab10052c9849242fe97084148e0ea805d5"
      url "https://github.com/owainlewis/neo/releases/download/v#{version}/neo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4f3396b9f71ca685187b898ed0e015ad3a6f10f74f2251b7b7a923782b5e0f37"
      url "https://github.com/owainlewis/neo/releases/download/v#{version}/neo_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f08ffc2de012f5dabf2c2265ec3f2e78f7b4d7b3304fb0472b23b4bccf0e825"
      url "https://github.com/owainlewis/neo/releases/download/v#{version}/neo_linux_arm64.tar.gz"
    end
  end

  name "neo"
  desc "Fast, minimalist coding agent written in Go"
  homepage "https://github.com/owainlewis/neo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "neo"

  # No zap stanza required

end
