# This file was generated by GoReleaser. DO NOT EDIT.
cask "neo" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "eb33023e65468d385fbfcb0a9208a2b55c7aa4989fb80edbf2661c4c947d6dc1"
      url "https://github.com/owainlewis/neo/releases/download/v#{version}/neo_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "995ec37b4199e8f57289144783651640d5fcfa75aaba31ab901c011df1ffec91"
      url "https://github.com/owainlewis/neo/releases/download/v#{version}/neo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e577ebb63960f5bfb58913c5dfe4a685871f0ab3ea6adc6a2a6427884d750c30"
      url "https://github.com/owainlewis/neo/releases/download/v#{version}/neo_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "427c5d637c0fca40ca9faa725b82e7619e7c52946e7aaf6e4f6412395abfdc3e"
      url "https://github.com/owainlewis/neo/releases/download/v#{version}/neo_linux_arm64.tar.gz"
    end
  end

  name "neo"
  desc "Fast, minimalist coding agent written in Go"
  homepage "https://github.com/owainlewis/neo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "neo"

  # No zap stanza required

end
