# This file was generated by GoReleaser. DO NOT EDIT.
cask "skills" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "eff9af784b3806f9afec15db5a1298a1d9996bd422e83c25d68bbc0b88048f3a"
      url "https://github.com/owainlewis/skills/releases/download/v#{version}/skills_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7204108d79cb66b4d28651552fb0a91be5ba627bb385bfb9e4dfe4d7d42c5ded"
      url "https://github.com/owainlewis/skills/releases/download/v#{version}/skills_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "86cfae39e23470939be4801860a1896f5534a24cb265d59b6441d9e904649e09"
      url "https://github.com/owainlewis/skills/releases/download/v#{version}/skills_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "61030cd586bcd5db923cae78a9e46444e7e4cc522dd0b48cd0070eb3c66ec3d5"
      url "https://github.com/owainlewis/skills/releases/download/v#{version}/skills_linux_arm64.tar.gz"
    end
  end

  name "skills"
  desc "Minimalist, agent-first installer for agent skills"
  homepage "https://github.com/owainlewis/skills"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skills"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/skills"]
    end
  end

  # No zap stanza required

end
