# This file was generated by GoReleaser. DO NOT EDIT.
cask "skills" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "039ca59070dad3a951a2cc724cc3c75aa27ff08ab37baac75170aae28f595f99"
      url "https://github.com/owainlewis/skills/releases/download/v#{version}/skills_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a424a3f7b8efecca21372f41ead03e7dffee005a72649217d3989937e309a8b3"
      url "https://github.com/owainlewis/skills/releases/download/v#{version}/skills_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "24a1fceb8edfe13a97d520caeb220afaa6490431fbaba979300fab7188a2c06a"
      url "https://github.com/owainlewis/skills/releases/download/v#{version}/skills_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a481b87b93d7b03f92508f09b8e50d4b618738281e7e32ac5bd4c369e1963592"
      url "https://github.com/owainlewis/skills/releases/download/v#{version}/skills_linux_arm64.tar.gz"
    end
  end

  name "skills"
  desc "Minimalist, agent-first installer for agent skills"
  homepage "https://github.com/owainlewis/skills"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skills"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/skills"]
    end
  end

  # No zap stanza required

end
