# This file was generated by GoReleaser. DO NOT EDIT.
cask "skills" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "7cc972c0db7c534b0ef50a9613237b6ecae75cc4fb371fe5285e7c6ae859e90a"
      url "https://github.com/owainlewis/skills/releases/download/v#{version}/skills_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b73613a6a978819f8cb2dd2a508b37324981989a2113bb98459a779c5043eeb5"
      url "https://github.com/owainlewis/skills/releases/download/v#{version}/skills_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "abb3f7dfcb8c5eae2dde42fa5eaccf416e7b382efbaf84eac6d6358cd8c4b219"
      url "https://github.com/owainlewis/skills/releases/download/v#{version}/skills_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ecaf8e37bd96a7e942c93b560a91c1caa71e2829b933dfa2793cfdaea31fc39f"
      url "https://github.com/owainlewis/skills/releases/download/v#{version}/skills_linux_arm64.tar.gz"
    end
  end

  name "skills"
  desc "Minimalist, agent-first installer for agent skills"
  homepage "https://github.com/owainlewis/skills"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skills"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/skills"]
    end
  end

  # No zap stanza required

end
